Add checks before preparing sigdata and enable submit
kadena-community/kadena-transfer-js pull request #50
Opened 2022-09-16 16:20 UTC by ggobugi27

Closes #45

2022-09-16 18:29 UTC, jmininger approved these changes

2022-09-19 08:52 UTC, alber70g requested changes
I suggest to run the formatter before committing. This will get syntax errors (missing braces etc) and gets it into a uniform format. 

These commands can be used if the IDE doesn't have prettier integration.

`prettier ./docs/xchain.js --check`
`prettier ./docs/xchain.js --write` (auto writes fixes to file)

2022-09-19 08:52 UTC, alber70g commented on docs/xchain.js
>      if (pactInfo[pactId]) {
This function needs to be `async`

2022-09-19 08:52 UTC, alber70g commented on docs/xchain.js
>            });
There's a closing curly brace missing somewhere here

2022-09-19 08:52 UTC, alber70g commented on docs/xchain.js
>        } catch (err) {
Else-statement isn't closed

2022-09-19 11:16 UTC, alber70g approved these changes

2022-09-19 11:19 UTC, merged